# Generated by Django 4.2.5 on 2023-09-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_aboutname_about_abouttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailUser', models.CharField(max_length=200)),
                ('messageUser', models.TextField()),
            ],
        ),
    ]
